const GET_SELLER = 'GET_SELLER';

const SHOW_DETAIL = "SHOW_DETAIL";

const HIDE_DETAIL = "HIDE_DETAIL";

const SHOW_COLLECT_FLAG = "SHOW_COLLECT_FLAG";

const GET_FOODS = "GET_FOODS";

const GET_RATINGS = "GET_RATINGS";

const GET_TEXT = "GET_TEXT";

const ADD_FOOD = "ADD_FOOD";

const CUT_FOOD = "CUT_FOOD";

const SHOW_CART = "SHOW_CART";

const SHOW_DETAIL_FOOD = "SHOW_DETAIL_FOOD";

const HIDE_CART = "HIDE_CART";

const CLEAR = "CLEAR";

export default{
	GET_SELLER,
  SHOW_DETAIL,
  HIDE_DETAIL,
  SHOW_COLLECT_FLAG,
  GET_FOODS,
  GET_RATINGS,
  GET_TEXT,
  ADD_FOOD,
  CUT_FOOD,
  SHOW_CART,
  SHOW_DETAIL_FOOD,
  HIDE_CART,
  CLEAR
}
